package com.sdj.dao;

import com.sdj.bean.EmotionText;
import com.sdj.bean.EmotionTextExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface EmotionTextMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table text
     *
     * @mbg.generated
     */
    long countByExample(EmotionTextExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table text
     *
     * @mbg.generated
     */
    int deleteByExample(EmotionTextExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table text
     *
     * @mbg.generated
     */
    int insert(EmotionText record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table text
     *
     * @mbg.generated
     */
    int insertSelective(EmotionText record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table text
     *
     * @mbg.generated
     */
    List<EmotionText> selectByExampleWithBLOBs(EmotionTextExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table text
     *
     * @mbg.generated
     */
    List<EmotionText> selectByExample(EmotionTextExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table text
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") EmotionText record, @Param("example") EmotionTextExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table text
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("record") EmotionText record, @Param("example") EmotionTextExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table text
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") EmotionText record, @Param("example") EmotionTextExample example);
}