package com.sdj.bean;

public class EmotionText {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column text.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column text.emotionlabel
     *
     * @mbg.generated
     */
    private Integer emotionlabel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column text.isnew
     *
     * @mbg.generated
     */
    private Integer isnew;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column text.textcontent
     *
     * @mbg.generated
     */
    private String textcontent;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column text.id
     *
     * @return the value of text.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column text.id
     *
     * @param id the value for text.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column text.emotionlabel
     *
     * @return the value of text.emotionlabel
     *
     * @mbg.generated
     */
    public Integer getEmotionlabel() {
        return emotionlabel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column text.emotionlabel
     *
     * @param emotionlabel the value for text.emotionlabel
     *
     * @mbg.generated
     */
    public void setEmotionlabel(Integer emotionlabel) {
        this.emotionlabel = emotionlabel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column text.isnew
     *
     * @return the value of text.isnew
     *
     * @mbg.generated
     */
    public Integer getIsnew() {
        return isnew;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column text.isnew
     *
     * @param isnew the value for text.isnew
     *
     * @mbg.generated
     */
    public void setIsnew(Integer isnew) {
        this.isnew = isnew;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column text.textcontent
     *
     * @return the value of text.textcontent
     *
     * @mbg.generated
     */
    public String getTextcontent() {
        return textcontent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column text.textcontent
     *
     * @param textcontent the value for text.textcontent
     *
     * @mbg.generated
     */
    public void setTextcontent(String textcontent) {
        this.textcontent = textcontent == null ? null : textcontent.trim();
    }

	@Override
	public String toString() {
		return "EmotionText [" + (id != null ? "id=" + id + ", " : "")
				+ (emotionlabel != null ? "emotionlabel=" + emotionlabel + ", " : "")
				+ (isnew != null ? "isnew=" + isnew + ", " : "")
				+ (textcontent != null ? "textcontent=" + textcontent : "") + "]";
	}
    
    
}